name: spider

on:
  push:
    branches: [ "main" ]
#    paths: 
#      - 'tc-spider/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: 删除旧的包
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd /${{secrets.USER}} && rm -rf yiboka && mkdir yiboka && cd yiboka"

    - name: 压缩
      run: tar -czvf code.tar.gz ./*
  
    - name: 上传包和Dockerfile到服务器中
      run: sshpass -p ${{secrets.PWD}} scp -r -o StrictHostKeyChecking=no ./code.tar.gz ${{secrets.USER}}@${{secrets.IP}}:/${{secrets.USER}}/yiboka

    - name: 解压
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd /${{secrets.USER}}/yiboka && tar -xzvf code.tar.gz"
  
  check: 
    runs-on: ubuntu-latest
    needs: [build]
    continue-on-error: true
    steps: 
    - name: 测试
      run: ls
    
    - name: 移除已存在compose
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "docker-compose stop yiboka && docker-compose rm yiboka
"

  deploye: 
    runs-on: ubuntu-latest
    needs: [build, check]
    steps:
    
    - name: 部署
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd /${{secrets.USER}}/yiboka && docker-compose -f docker-compose.yml up -d yiboka"
    
