name: yiboka

on:
  push:
    branches: [ "master" ]
#    paths: 
#      - 'tc-spider/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        shell: bash
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3

    - name: 删除旧的包
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd /home/ubuntu && rm -rf acgfaka && mkdir acgfaka && cd acgfaka"

    - name: 压缩
      run: tar -czvf code.tar.gz ./* .[!.]*
  
    - name: 上传包和Dockerfile到服务器中
      run: sshpass -p ${{secrets.PWD}} scp -r -o StrictHostKeyChecking=no ./code.tar.gz ${{secrets.USER}}@${{secrets.IP}}:/home/ubuntu/acgfaka

    - name: 解压
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "cd /home/ubuntu/acgfaka && tar -xzvf code.tar.gz"
  
  deploye: 
    runs-on: ubuntu-latest
    needs: [build]
    steps: 
    - name: 复制文件
      run: ls
    
    - name: 复制文件到目录，并覆盖
      run: sshpass -p ${{secrets.PWD}} ssh -o StrictHostKeyChecking=no ${{secrets.USER}}@${{secrets.IP}} "sudo cp /home/ubuntu/acgfaka/* /www/wwwroot/acgfaka"

    
